### ISSUE TITLE
todomvc demo: signals replay doesn't work

### ISSUE THREAD

**Issue by Guria** [christianalfoni/cerebral-angular-immutable-store#2]
Just tried to rewind signals in Cerebral Debugger on ToDoMVC demo. Debugger shows recorded signals but rewinding doesn't updates page state.
![](http://i.imgur.com/sdJmN0i.gif)

**Comment by christianalfoni** [comment]
Ah, crap, sorry. I forgot to implement a hook change in Cerebral. It is fixed now. v0.3.1 :-)
